[package]
name = "rengine"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["mike@desertrat.io"]
[features]
default = ["blas-apple"]
blas-apple = ["blas-src/accelerate"]

[dependencies]
cargo-show-asm = "0.2.57"
ndarray-linalg = { version = "0.18.1", default-features = false }
rayon = "1.11.0"
blas-src = { version = "0.14.0", features = ["accelerate"] }
blas = { version = "0.23.0", default-features = true }


